import Foundation

/// QC3: what the sender does not send without "Send Anyway" when `clip.block_sensitive` is on.
public enum SensitiveContent {
    /// Pasteboard types that password managers and generators put on concealed items (nspasteboard.org).
    public static let pasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]

    private static let maxLength = 256
    private static let digitRange = 13...19
    /// A run of digits with single spaces or hyphens between groups, not touching other digits.
    private static let run = try? NSRegularExpression(pattern: "(?<![0-9])[0-9](?:[ -]?[0-9]){12,}(?![0-9])")

    /// Text of at most 256 characters with a run of 13–19 digits that passes the Luhn check (the same rule as the
    /// Android app).
    public static func looksLikeCardNumber(_ text: String) -> Bool {
        let utf16 = text.utf16
        guard utf16.count <= maxLength, let run else { return false }
        let range = NSRange(location: 0, length: utf16.count)
        return run.matches(in: text, range: range).contains { match in
            guard let span = Range(match.range, in: text) else { return false }
            let digits = text[span].compactMap(\.wholeNumberValue)
            return digitRange.contains(digits.count) && luhn(digits)
        }
    }

    static func luhn(_ digits: [Int]) -> Bool {
        var sum = 0
        for (index, digit) in digits.reversed().enumerated() {
            var value = digit
            if index % 2 == 1 {
                value *= 2
                if value > 9 { value -= 9 }
            }
            sum += value
        }
        return sum % 10 == 0
    }
}
