"""Type-safe Swift accessors (`L10n`) for the catalog strings of the Apple apps (0.12.2)."""
from __future__ import annotations

from strings_catalog import SOURCE_LANGUAGE, Entry, swift_path

ACCESSORS_FILE = "Sources/HLLocalization/Generated/L10n.swift"
_HEADER = (
    "// Generated by Scripts/generate-strings.py from shared/strings/ui-strings.json.\n"
    "// Do not edit: change the catalog (docs first), run the script, check with --check.\n"
)


def _source_text(entry: Entry) -> str:
    text = entry.texts[SOURCE_LANGUAGE]
    if isinstance(text, dict):
        return " | ".join(f"{category}: {value}" for category, value in sorted(text.items()))
    return text


def _member(entry: Entry, name: str, indent: str) -> str:
    doc = f"{indent}/// {' '.join(_source_text(entry).split())}\n"
    if not entry.args:
        return doc + f'{indent}public static var {name}: String {{ L10nLookup.string("{entry.key}") }}\n'
    parameters = ", ".join(f"{arg.swift_label}: {arg.swift_type}" for arg in entry.args)
    values = ", ".join(arg.swift_label for arg in entry.args)
    bare = name.strip("`")
    return (
        doc
        + f"{indent}public static func {bare}({parameters}) -> String {{\n"
        + f'{indent}    L10nLookup.format("{entry.key}", {values})\n'
        + f"{indent}}}\n"
    )


def _render_tree(tree: dict, indent: str) -> str:
    out = []
    for name, node in tree.items():
        if isinstance(node, dict):
            out.append(f"{indent}public enum {name} {{\n")
            out.append(_render_tree(node, indent + "    "))
            out.append(f"{indent}}}\n")
        else:
            out.append(_member(node, name, indent))
    return "".join(out)


def render_accessors(entries: list[Entry]) -> str:
    tree: dict = {}
    for entry in sorted(entries, key=lambda item: item.key):
        groups, member = swift_path(entry.key)
        node = tree
        for group in groups:
            node = node.setdefault(group, {})
            if not isinstance(node, dict):
                raise ValueError(f"{entry.key}: '{group}' is both a string and a group")
        if member in node:
            raise ValueError(f"{entry.key}: accessor '{member}' already exists")
        node[member] = entry
    body = _render_tree(tree, "    ")
    return (
        _HEADER
        + "\n/// Every user-facing string of the Apple apps, from the shared catalog (C20, 0.12). Code never\n"
        + "/// spells UI text out: `Text(L10n.Status.connecting)`, `L10n.Pairing.pairedWith(deviceName: name)`.\n"
        + "public enum L10n {\n"
        + body
        + "}\n"
    )


def render_swift_accessors(entries: list[Entry]) -> dict[str, str]:
    return {ACCESSORS_FILE: render_accessors([entry for entry in entries if entry.is_apple])}
