import SwiftUI

/// The brand mark (the signal fire on its mountain) for the welcome screens: a vector image with light and dark
/// versions from the package's `Images.xcassets`, generated by the hub's `tools/brand/build_brand_assets.py`.
/// Decorative: the title next to it names the app, so VoiceOver skips the image.
public struct HLBrandMark: View {
    private let height: CGFloat

    /// - Parameter height: Height in points; the width follows the mark's 904:760 proportions.
    public init(height: CGFloat = 72) {
        self.height = height
    }

    public var body: some View {
        #if HL_COMMAND_LINE_TOOLS_ONLY
        // Without Xcode the asset catalog isn't bundled; keep the layout's space so the screen reads the same.
        Color.clear.frame(width: height * 904 / 760, height: height)
        #else
        Image("brand-mark", bundle: .module)
            .resizable()
            .scaledToFit()
            .frame(height: height)
            .accessibilityHidden(true)
        #endif
    }
}
